server:
  port: 8081
  servlet:
    context-path: /client

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/bank-client
    username: user
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
