server:
  servlet:
    context-path: /account

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:account-service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:postgresql://localhost:5432/account-service
    username:
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
