server:
  port: 8082

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/bank-account
    username: user
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
